import { DestinationId, DestinationMeta, Place } from '../types';

export const DESTINATIONS: Record<DestinationId, DestinationMeta> = {
  kolkata: {
    id: 'kolkata',
    name: 'Kolkata',
    subtitle: 'City of Joy & Grand Architecture',
    state: 'West Bengal',
    center: [22.5626, 88.3630],
    zoom: 13,
    heroImage: 'https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=1200&q=80',
    description: 'Colonial heritage, vibrant cultural tapestry, historic riverfronts, and quintessential Bengali culinary masterworks.',
    demoScenario: {
      title: 'Kolkata Heritage & Culture Day',
      description: 'Outdoor afternoon park trip vulnerable to sudden monsoon rainstorm while protecting an 8:00 PM dinner reservation.',
      triggerName: 'Simulate Heavy Rain',
      triggerType: 'WEATHER',
      defaultTripPlaces: [
        'kol_vic_mem',
        'kol_ind_mus',
        'kol_bengali_lunch',
        'kol_eco_park',
        'kol_new_market',
        'kol_dinner_parkst'
      ]
    }
  },
  nainital: {
    id: 'nainital',
    name: 'Nainital',
    subtitle: 'Lake City in the Kumaon Foothills',
    state: 'Uttarakhand',
    center: [29.3919, 79.4542],
    zoom: 14,
    heroImage: 'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=1200&q=80',
    description: 'Emerald crescent lakes, sacred hill shrines, colonial estates, and breathtaking views of snow-capped Himalayan peaks.',
    demoScenario: {
      title: 'Nainital Lake & Ridge Tour',
      description: 'Mountain ridge viewpoint affected by afternoon dense fog & storm warning requiring timely lakefront substitution.',
      triggerName: 'Simulate Mountain Weather Alert',
      triggerType: 'WEATHER',
      defaultTripPlaces: [
        'nai_lake',
        'nai_temple',
        'nai_lunch',
        'nai_snow_view',
        'nai_mall_road'
      ]
    }
  },
  darjeeling: {
    id: 'darjeeling',
    name: 'Darjeeling',
    subtitle: 'Queen of the Hills & Toy Train',
    state: 'West Bengal',
    center: [27.0410, 88.2663],
    zoom: 14,
    heroImage: 'https://images.unsplash.com/photo-1544735716-392fe2489ffa?auto=format&fit=crop&w=1200&q=80',
    description: 'Panoramic sunrise over Kanchenjunga, UNESCO Himalayan railway, fragrant tea gardens, and Tibetan monastic serenity.',
    demoScenario: {
      title: 'Darjeeling Sunrise to Tea Country',
      description: 'Narrow hill highway vehicle blockage causes 45-min transit bottleneck threatening afternoon zoo schedule.',
      triggerName: 'Simulate Hill Road Traffic Delay',
      triggerType: 'TRAFFIC',
      defaultTripPlaces: [
        'dar_tiger_hill',
        'dar_batasia',
        'dar_keventers',
        'dar_hmi',
        'dar_mall_road'
      ]
    }
  },
  kashmir: {
    id: 'kashmir',
    name: 'Kashmir Valley',
    subtitle: 'Paradise on Earth — Srinagar & Beyond',
    state: 'Jammu & Kashmir',
    center: [34.0837, 74.8370],
    zoom: 12,
    heroImage: 'https://images.unsplash.com/photo-1595815771614-ade9d652a65d?auto=format&fit=crop&w=1200&q=80',
    description: 'Shikaras on mirror-still Dal Lake, terraced Mughal gardens, alpine meadows of Gulmarg, and legendary Kashmiri hospitality.',
    demoScenario: {
      title: 'Srinagar Gardens & Lake Odyssey',
      description: 'Combined boulevard congestion and tourist procession delay threatening sunset Pari Mahal overlook and dinner.',
      triggerName: 'Simulate Traffic + Schedule Delay',
      triggerType: 'USER_DELAY',
      defaultTripPlaces: [
        'kas_dal_lake',
        'kas_mughal_garden',
        'kas_wazwan_lunch',
        'kas_pari_mahal',
        'kas_dinner'
      ]
    }
  }
};

export const PLACES_DATABASE: Record<DestinationId, Place[]> = {
  kolkata: [
    {
      id: 'kol_vic_mem',
      name: 'Victoria Memorial',
      city: 'Kolkata',
      category: 'history',
      latitude: 22.5448,
      longitude: 88.3426,
      estimated_duration_minutes: 120,
      indoor: true,
      outdoor: true,
      priority: 'must_do',
      description: 'Grand white marble monument opened in 1921, surrounded by 64 acres of manicured gardens and housing 25 galleries of rare art.',
      opening_hours: { open: '10:00', close: '18:00', closedDays: ['Monday'] },
      tags: ['history', 'architecture', 'iconic', 'museum'],
      costEstimateINR: 50,
      bestTimeOfDay: 'morning'
    },
    {
      id: 'kol_ind_mus',
      name: 'Indian Museum',
      city: 'Kolkata',
      category: 'history',
      latitude: 22.5579,
      longitude: 88.3512,
      estimated_duration_minutes: 95,
      indoor: true,
      outdoor: false,
      priority: 'must_do',
      description: 'The oldest and largest museum in India, founded in 1814, featuring ancient Gandharan sculptures, fossils, and an Egyptian mummy.',
      opening_hours: { open: '10:00', close: '17:00', closedDays: ['Monday'] },
      tags: ['history', 'indoor', 'antiquities', 'culture'],
      costEstimateINR: 50,
      bestTimeOfDay: 'morning'
    },
    {
      id: 'kol_st_paul',
      name: "St. Paul's Cathedral",
      city: 'Kolkata',
      category: 'culture',
      latitude: 22.5443,
      longitude: 88.3468,
      estimated_duration_minutes: 45,
      indoor: true,
      outdoor: false,
      priority: 'preferred',
      description: 'Gothic revival cathedral with magnificent stained glass windows designed by Sir Edward Burne-Jones, located near Maidan.',
      opening_hours: { open: '09:00', close: '17:30' },
      tags: ['architecture', 'peaceful', 'heritage'],
      costEstimateINR: 0,
      bestTimeOfDay: 'morning'
    },
    {
      id: 'kol_bengali_lunch',
      name: 'Bengali Lunch (6 Ballygunge Place)',
      city: 'Kolkata',
      category: 'food',
      latitude: 22.5273,
      longitude: 88.3644,
      estimated_duration_minutes: 60,
      indoor: true,
      outdoor: false,
      priority: 'must_do',
      description: 'Iconic heritage restaurant set in a century-old mansion serving traditional Kosha Mangsho, Daab Chingri, and Mishti Doi.',
      opening_hours: { open: '12:00', close: '16:00' },
      tags: ['food', 'bengali', 'culinary', 'indoor'],
      costEstimateINR: 800,
      bestTimeOfDay: 'afternoon'
    },
    {
      id: 'kol_eco_park',
      name: 'Eco Park (Prakriti Tirtha)',
      city: 'Kolkata',
      category: 'nature',
      latitude: 22.5976,
      longitude: 88.4682,
      estimated_duration_minutes: 120,
      indoor: false,
      outdoor: true,
      priority: 'preferred',
      description: 'Vast 480-acre ecological recreation park with Seven Wonders replicas, boating lake, butterfly gardens, and landscaped trails.',
      opening_hours: { open: '12:00', close: '20:30', closedDays: ['Monday'] },
      tags: ['nature', 'outdoor', 'scenic', 'gardens'],
      costEstimateINR: 30,
      bestTimeOfDay: 'afternoon'
    },
    {
      id: 'kol_new_market',
      name: 'New Market (Hogg Market)',
      city: 'Kolkata',
      category: 'shopping',
      latitude: 22.5601,
      longitude: 88.3528,
      estimated_duration_minutes: 90,
      indoor: true,
      outdoor: false,
      priority: 'optional',
      description: 'Historic Victorian brick shopping arcade built in 1874 with over 2,000 stalls selling handicrafts, textiles, teas, and Kolkata confections.',
      opening_hours: { open: '10:00', close: '20:30', closedDays: ['Sunday'] },
      tags: ['shopping', 'indoor', 'souvenirs', 'textiles'],
      costEstimateINR: 300,
      bestTimeOfDay: 'evening'
    },
    {
      id: 'kol_dinner_parkst',
      name: 'Dinner at Park Street Heritage (Peter Cat)',
      city: 'Kolkata',
      category: 'food',
      latitude: 22.5532,
      longitude: 88.3524,
      estimated_duration_minutes: 90,
      indoor: true,
      outdoor: false,
      priority: 'must_do',
      description: 'Legendary Park Street restaurant revered for its signature Chelo Kebab, timeless colonial ambiance, and warm hospitality.',
      opening_hours: { open: '19:00', close: '23:30' },
      tags: ['food', 'iconic', 'indoor', 'reservation'],
      costEstimateINR: 1000,
      bestTimeOfDay: 'evening'
    },
    {
      id: 'kol_howrah_bridge',
      name: 'Howrah Bridge (Rabindra Setu)',
      city: 'Kolkata',
      category: 'culture',
      latitude: 22.5851,
      longitude: 88.3468,
      estimated_duration_minutes: 40,
      indoor: false,
      outdoor: true,
      priority: 'preferred',
      description: 'Massive balanced cantilever steel bridge spanning the Hooghly River without nuts or bolts, carrying over 100,000 vehicles daily.',
      opening_hours: { open: '00:00', close: '23:59' },
      tags: ['landmark', 'historic', 'photo_spot'],
      costEstimateINR: 0,
      bestTimeOfDay: 'morning'
    },
    {
      id: 'kol_prinsep_ghat',
      name: 'Prinsep Ghat Riverfront',
      city: 'Kolkata',
      category: 'scenic',
      latitude: 22.5562,
      longitude: 88.3325,
      estimated_duration_minutes: 60,
      indoor: false,
      outdoor: true,
      priority: 'optional',
      description: 'Picturesque Greek Palladian portico on the riverbank overlooking Vidyasagar Setu, famous for traditional wooden boat rides at sunset.',
      opening_hours: { open: '06:00', close: '22:00' },
      tags: ['sunset', 'river', 'scenic', 'romantic'],
      costEstimateINR: 150,
      bestTimeOfDay: 'sunset'
    },
    {
      id: 'kol_science_city',
      name: 'Science City',
      city: 'Kolkata',
      category: 'culture',
      latitude: 22.5401,
      longitude: 88.3963,
      estimated_duration_minutes: 110,
      indoor: true,
      outdoor: true,
      priority: 'optional',
      description: 'Major science center featuring Space Odyssey, Earth Exploration Hall, and 3D theatre halls ideal for families.',
      opening_hours: { open: '09:00', close: '19:00' },
      tags: ['education', 'science', 'family'],
      costEstimateINR: 70,
      bestTimeOfDay: 'afternoon'
    },
    {
      id: 'kol_college_st',
      name: 'College Street Boi Para & Coffee House',
      city: 'Kolkata',
      category: 'culture',
      latitude: 22.5744,
      longitude: 88.3639,
      estimated_duration_minutes: 75,
      indoor: true,
      outdoor: true,
      priority: 'preferred',
      description: "The world's largest second-hand book market and the legendary Indian Coffee House, epicenter of Bengali intellectual discourse.",
      opening_hours: { open: '10:00', close: '20:00' },
      tags: ['books', 'coffee', 'intellectual', 'heritage'],
      costEstimateINR: 150,
      bestTimeOfDay: 'afternoon'
    },
    {
      id: 'kol_marble_palace',
      name: 'Marble Palace Mansion',
      city: 'Kolkata',
      category: 'history',
      latitude: 22.5828,
      longitude: 88.3598,
      estimated_duration_minutes: 60,
      indoor: true,
      outdoor: false,
      priority: 'optional',
      description: 'Neoclassical mansion built in 1835 with marble floors, Victorian furniture, and original paintings by Rubens and Reynolds.',
      opening_hours: { open: '10:00', close: '16:00', closedDays: ['Monday', 'Thursday'] },
      tags: ['heritage', 'art', 'historic'],
      costEstimateINR: 0,
      bestTimeOfDay: 'morning'
    }
  ],
  nainital: [
    {
      id: 'nai_lake',
      name: 'Naini Lake (Boating & Promenade)',
      city: 'Nainital',
      category: 'nature',
      latitude: 29.3919,
      longitude: 79.4542,
      estimated_duration_minutes: 75,
      indoor: false,
      outdoor: true,
      priority: 'must_do',
      description: 'Crescent-shaped eye-like freshwater lake encircled by seven forested hills. Famous for yachting and rowing.',
      opening_hours: { open: '06:00', close: '18:30' },
      tags: ['lake', 'boating', 'scenic', 'outdoor'],
      costEstimateINR: 300,
      bestTimeOfDay: 'morning'
    },
    {
      id: 'nai_temple',
      name: 'Naina Devi Temple',
      city: 'Nainital',
      category: 'spiritual',
      latitude: 29.3942,
      longitude: 79.4589,
      estimated_duration_minutes: 45,
      indoor: false,
      outdoor: true,
      priority: 'must_do',
      description: 'Ancient Hindu Shakti Peeth shrine situated at the northern edge of Naini Lake dedicated to Goddess Naina Devi.',
      opening_hours: { open: '06:00', close: '21:00' },
      tags: ['spiritual', 'temple', 'peaceful'],
      costEstimateINR: 0,
      bestTimeOfDay: 'morning'
    },
    {
      id: 'nai_lunch',
      name: "Lunch at Sakley's Mountain Café",
      city: 'Nainital',
      category: 'food',
      latitude: 29.3905,
      longitude: 79.4566,
      estimated_duration_minutes: 60,
      indoor: true,
      outdoor: false,
      priority: 'preferred',
      description: 'Colonial hill cafe opened in 1944 known for rustic wood interiors, artisan pies, roasts, and specialty coffees.',
      opening_hours: { open: '11:00', close: '22:00' },
      tags: ['cafe', 'bakery', 'indoor', 'food'],
      costEstimateINR: 650,
      bestTimeOfDay: 'afternoon'
    },
    {
      id: 'nai_snow_view',
      name: 'Snow View Point (Ropeway)',
      city: 'Nainital',
      category: 'scenic',
      latitude: 29.4005,
      longitude: 79.4593,
      estimated_duration_minutes: 90,
      indoor: false,
      outdoor: true,
      priority: 'preferred',
      description: 'Summit vantage point at 2,270m offering unobstructed views of Nanda Devi, Trishul, and Nanda Kot snow peaks.',
      opening_hours: { open: '10:00', close: '17:00' },
      tags: ['mountain_view', 'ropeway', 'outdoor', 'scenic'],
      costEstimateINR: 300,
      bestTimeOfDay: 'afternoon'
    },
    {
      id: 'nai_mall_road',
      name: 'The Mall Road Evening Walk & Shops',
      city: 'Nainital',
      category: 'shopping',
      latitude: 29.3888,
      longitude: 79.4581,
      estimated_duration_minutes: 75,
      indoor: false,
      outdoor: true,
      priority: 'preferred',
      description: 'Lakeside pedestrian promenade linking Mallital and Tallital lined with wooden handicraft shops and handmade candle bazaars.',
      opening_hours: { open: '09:00', close: '22:00' },
      tags: ['walk', 'shopping', 'lakefront', 'evening'],
      costEstimateINR: 200,
      bestTimeOfDay: 'evening'
    },
    {
      id: 'nai_eco_caves',
      name: 'Eco Cave Gardens',
      city: 'Nainital',
      category: 'adventure',
      latitude: 29.3957,
      longitude: 79.4446,
      estimated_duration_minutes: 60,
      indoor: true,
      outdoor: true,
      priority: 'optional',
      description: 'Network of six natural interconnected animal-shaped rock caves (Tiger, Panther, Bat) lit with petroleum lamps.',
      opening_hours: { open: '09:30', close: '17:30' },
      tags: ['caves', 'adventure', 'indoor'],
      costEstimateINR: 60,
      bestTimeOfDay: 'afternoon'
    },
    {
      id: 'nai_tiffin_top',
      name: 'Tiffin Top (Dorothy’s Seat)',
      city: 'Nainital',
      category: 'scenic',
      latitude: 29.3846,
      longitude: 79.4449,
      estimated_duration_minutes: 120,
      indoor: false,
      outdoor: true,
      priority: 'optional',
      description: 'Terraced stone perch atop Ayarpatta Hill (2,292m) honoring Dorothy Kellet, offering 360-degree panorama of Nainital valley.',
      opening_hours: { open: '06:00', close: '18:00' },
      tags: ['hiking', 'trek', 'scenic', 'panoramic'],
      costEstimateINR: 0,
      bestTimeOfDay: 'morning'
    },
    {
      id: 'nai_gov_house',
      name: "Governor's House (Raj Bhavan)",
      city: 'Nainital',
      category: 'history',
      latitude: 29.3789,
      longitude: 79.4601,
      estimated_duration_minutes: 60,
      indoor: true,
      outdoor: true,
      priority: 'optional',
      description: 'Victorian Gothic mansion styled after Buckingham Palace, featuring sprawling oak forests and an 18-hole golf course.',
      opening_hours: { open: '11:00', close: '16:00' },
      tags: ['heritage', 'architecture', 'gardens'],
      costEstimateINR: 50,
      bestTimeOfDay: 'afternoon'
    }
  ],
  darjeeling: [
    {
      id: 'dar_tiger_hill',
      name: 'Tiger Hill Sunrise (Mt. Kanchenjunga)',
      city: 'Darjeeling',
      category: 'scenic',
      latitude: 26.9953,
      longitude: 88.2858,
      estimated_duration_minutes: 90,
      indoor: false,
      outdoor: true,
      priority: 'must_do',
      description: 'Legendary dawn viewpoint where early morning rays illuminate the third highest peak in the world in golden hues.',
      opening_hours: { open: '04:00', close: '18:00' },
      tags: ['sunrise', 'kanchenjunga', 'mountains', 'scenic'],
      costEstimateINR: 100,
      bestTimeOfDay: 'morning'
    },
    {
      id: 'dar_batasia',
      name: 'Batasia Loop & War Memorial',
      city: 'Darjeeling',
      category: 'culture',
      latitude: 27.0169,
      longitude: 88.2464,
      estimated_duration_minutes: 60,
      indoor: false,
      outdoor: true,
      priority: 'must_do',
      description: 'Spiral railway loop where the Toy Train navigates a 360-degree curve amid landscaped floral gardens and Gorkha war memorial.',
      opening_hours: { open: '05:00', close: '18:00' },
      tags: ['railway', 'gardens', 'monument', 'scenic'],
      costEstimateINR: 20,
      bestTimeOfDay: 'morning'
    },
    {
      id: 'dar_keventers',
      name: "Breakfast at Keventer's Open Terrace",
      city: 'Darjeeling',
      category: 'food',
      latitude: 27.0416,
      longitude: 88.2655,
      estimated_duration_minutes: 50,
      indoor: false,
      outdoor: true,
      priority: 'preferred',
      description: 'Century-old British colonial tearoom famous for English platters, hot cocoa, sausages, and mountain view terrace.',
      opening_hours: { open: '07:30', close: '19:30' },
      tags: ['breakfast', 'colonial', 'terrace', 'food'],
      costEstimateINR: 400,
      bestTimeOfDay: 'morning'
    },
    {
      id: 'dar_hmi',
      name: 'Himalayan Mountaineering Institute & Zoo',
      city: 'Darjeeling',
      category: 'history',
      latitude: 27.0583,
      longitude: 88.2575,
      estimated_duration_minutes: 100,
      indoor: true,
      outdoor: true,
      priority: 'must_do',
      description: 'Mountaineering academy founded in 1954 by Tenzing Norgay with Everest expedition museum and high-altitude wildlife park.',
      opening_hours: { open: '08:30', close: '16:30', closedDays: ['Thursday'] },
      tags: ['everest', 'museum', 'indoor', 'wildlife'],
      costEstimateINR: 110,
      bestTimeOfDay: 'afternoon'
    },
    {
      id: 'dar_mall_road',
      name: 'Chowrasta Mall Road & Oxford Book Shop',
      city: 'Darjeeling',
      category: 'shopping',
      latitude: 27.0435,
      longitude: 88.2673,
      estimated_duration_minutes: 75,
      indoor: false,
      outdoor: true,
      priority: 'preferred',
      description: 'Vehicular-free town square surrounded by cedar trees, heritage tea boutiques, and street benches looking across pine valleys.',
      opening_hours: { open: '08:00', close: '20:30' },
      tags: ['walk', 'tea', 'souvenirs', 'evening'],
      costEstimateINR: 150,
      bestTimeOfDay: 'evening'
    },
    {
      id: 'dar_tea_estate',
      name: 'Happy Valley Tea Estate Tour',
      city: 'Darjeeling',
      category: 'culture',
      latitude: 27.0532,
      longitude: 88.2608,
      estimated_duration_minutes: 80,
      indoor: true,
      outdoor: true,
      priority: 'optional',
      description: 'Historic organic tea garden established in 1854 explaining orthodox rolling, fermentation, and tasting of Muscatel flush teas.',
      opening_hours: { open: '08:00', close: '16:30', closedDays: ['Monday'] },
      tags: ['tea', 'plantation', 'tasting'],
      costEstimateINR: 150,
      bestTimeOfDay: 'afternoon'
    },
    {
      id: 'dar_peace_pagoda',
      name: 'Japanese Peace Pagoda',
      city: 'Darjeeling',
      category: 'spiritual',
      latitude: 27.0298,
      longitude: 88.2579,
      estimated_duration_minutes: 50,
      indoor: true,
      outdoor: true,
      priority: 'optional',
      description: 'Buddhist stupa designed by Nichidatsu Fuji showcasing four golden avatars of Lord Buddha and quiet meditation hall.',
      opening_hours: { open: '04:30', close: '19:00' },
      tags: ['buddhism', 'peaceful', 'spiritual'],
      costEstimateINR: 0,
      bestTimeOfDay: 'afternoon'
    },
    {
      id: 'dar_glenarys',
      name: "Glenary's Bakery, Café & Restaurant",
      city: 'Darjeeling',
      category: 'food',
      latitude: 27.0422,
      longitude: 88.2661,
      estimated_duration_minutes: 60,
      indoor: true,
      outdoor: false,
      priority: 'preferred',
      description: 'Two-story vintage landmark offering Darjeeling first-flush tea, Apple strudels, sizzlers, and live evening acoustic music.',
      opening_hours: { open: '07:00', close: '22:00' },
      tags: ['bakery', 'dinner', 'indoor', 'heritage'],
      costEstimateINR: 600,
      bestTimeOfDay: 'evening'
    }
  ],
  kashmir: [
    {
      id: 'kas_dal_lake',
      name: 'Dal Lake Shikara Ride (Srinagar)',
      city: 'Kashmir',
      region: 'Srinagar',
      category: 'nature',
      latitude: 34.0837,
      longitude: 74.8370,
      estimated_duration_minutes: 90,
      indoor: false,
      outdoor: true,
      priority: 'must_do',
      description: 'Iconic cedarwood boat glide past floating vegetable markets, lotus gardens, and ornate Victorian wooden houseboats on Dal Lake.',
      opening_hours: { open: '06:00', close: '20:00' },
      tags: ['lake', 'shikara', 'iconic', 'scenic'],
      costEstimateINR: 700,
      bestTimeOfDay: 'morning'
    },
    {
      id: 'kas_mughal_garden',
      name: 'Nishat Bagh Mughal Gardens (Srinagar)',
      city: 'Kashmir',
      region: 'Srinagar',
      category: 'culture',
      latitude: 34.1256,
      longitude: 74.8812,
      estimated_duration_minutes: 75,
      indoor: false,
      outdoor: true,
      priority: 'must_do',
      description: 'The Garden of Bliss, built in 1633 by Asif Khan. Twelve terraced stone water cascades facing the Zabarwan mountain range.',
      opening_hours: { open: '09:00', close: '19:00' },
      tags: ['gardens', 'mughal', 'heritage', 'scenic'],
      costEstimateINR: 24,
      bestTimeOfDay: 'morning'
    },
    {
      id: 'kas_wazwan_lunch',
      name: 'Traditional Kashmiri Wazwan Lunch (Ahdoos)',
      city: 'Kashmir',
      region: 'Srinagar',
      category: 'food',
      latitude: 34.0716,
      longitude: 74.8198,
      estimated_duration_minutes: 60,
      indoor: true,
      outdoor: false,
      priority: 'must_do',
      description: 'Heritage culinary institution established in 1918 serving 36-course royal Wazwan featuring Rista, Rogan Josh, and Gushtaba.',
      opening_hours: { open: '12:00', close: '22:30' },
      tags: ['wazwan', 'kashmiri', 'indoor', 'food'],
      costEstimateINR: 900,
      bestTimeOfDay: 'afternoon'
    },
    {
      id: 'kas_pari_mahal',
      name: 'Pari Mahal Palace of Fairies (Srinagar)',
      city: 'Kashmir',
      region: 'Srinagar',
      category: 'history',
      latitude: 34.0833,
      longitude: 74.8767,
      estimated_duration_minutes: 70,
      indoor: false,
      outdoor: true,
      priority: 'preferred',
      description: 'Six-terraced Mughal observatory built by Prince Dara Shikoh overlooking Dal Lake and Royal Springs golf course at sunset.',
      opening_hours: { open: '09:30', close: '19:30' },
      tags: ['palace', 'viewpoint', 'sunset', 'history'],
      costEstimateINR: 24,
      bestTimeOfDay: 'sunset'
    },
    {
      id: 'kas_dinner',
      name: 'Lakeside Kashmiri Kahwa & Dinner (Lalit Grand Palace)',
      city: 'Kashmir',
      region: 'Srinagar',
      category: 'food',
      latitude: 34.0772,
      longitude: 74.8519,
      estimated_duration_minutes: 90,
      indoor: true,
      outdoor: false,
      priority: 'must_do',
      description: 'Former Maharaja Gulab Singh palace overlooking Dal Lake offering saffron-infused Kahwa tea, fireplace dining, and traditional music.',
      opening_hours: { open: '19:00', close: '23:00' },
      tags: ['palace', 'dinner', 'saffron', 'reservation'],
      costEstimateINR: 1400,
      bestTimeOfDay: 'evening'
    },
    {
      id: 'kas_shalimar',
      name: 'Shalimar Bagh Royal Garden (Srinagar)',
      city: 'Kashmir',
      region: 'Srinagar',
      category: 'culture',
      latitude: 34.1481,
      longitude: 74.8728,
      estimated_duration_minutes: 70,
      indoor: false,
      outdoor: true,
      priority: 'preferred',
      description: 'The crowning garden of Mughal Emperor Jahangir built for Empress Nur Jahan in 1619 with black marble pavilions and sycamore chinar trees.',
      opening_hours: { open: '09:00', close: '19:00' },
      tags: ['mughal', 'chinar', 'gardens'],
      costEstimateINR: 24,
      bestTimeOfDay: 'afternoon'
    },
    {
      id: 'kas_shankaracharya',
      name: 'Shankaracharya Temple Hilltop (Srinagar)',
      city: 'Kashmir',
      region: 'Srinagar',
      category: 'spiritual',
      latitude: 34.0725,
      longitude: 74.8465,
      estimated_duration_minutes: 60,
      indoor: false,
      outdoor: true,
      priority: 'optional',
      description: 'Historic stone Shiva shrine atop Gopadari Hill (1,100ft above city plain) dating back to 200 BC offering bird’s-eye views of Srinagar.',
      opening_hours: { open: '07:30', close: '17:00' },
      tags: ['spiritual', 'temple', 'hilltop'],
      costEstimateINR: 0,
      bestTimeOfDay: 'morning'
    },
    {
      id: 'kas_gulmarg_gondola',
      name: 'Gulmarg Gondola & Apharwat Peak (Gulmarg)',
      city: 'Kashmir',
      region: 'Gulmarg (50 km from Srinagar)',
      category: 'adventure',
      latitude: 34.0484,
      longitude: 74.3805,
      estimated_duration_minutes: 180,
      indoor: false,
      outdoor: true,
      priority: 'preferred',
      description: "One of the world's highest cable cars rising to 3,980m offering year-round snow fields, skiing slopes, and alpine pine forests.",
      opening_hours: { open: '09:00', close: '16:30' },
      tags: ['snow', 'gondola', 'cable_car', 'alpine'],
      costEstimateINR: 950,
      bestTimeOfDay: 'morning'
    }
  ]
};

/**
 * Calculates distance in kilometers between two geo coordinates using Haversine formula
 */
export function calculateDistanceKm(lat1: number, lon1: number, lat2: number, lon2: number): number {
  const R = 6371; // Earth's radius in km
  const dLat = ((lat2 - lat1) * Math.PI) / 180;
  const dLon = ((lon2 - lon1) * Math.PI) / 180;
  const a =
    Math.sin(dLat / 2) * Math.sin(dLat / 2) +
    Math.cos((lat1 * Math.PI) / 180) *
      Math.cos((lat2 * Math.PI) / 180) *
      Math.sin(dLon / 2) *
      Math.sin(dLon / 2);
  const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  return Math.round(R * c * 10) / 10;
}

/**
 * Estimates realistic travel time in minutes based on distance, terrain, and city transit conditions
 */
export function estimateTravelMinutes(dest: DestinationId, lat1: number, lon1: number, lat2: number, lon2: number): number {
  const dist = calculateDistanceKm(lat1, lon1, lat2, lon2);
  if (dist < 0.2) return 5;

  // Mountain roads (Darjeeling, Nainital, Kashmir mountain paths) vs Kolkata urban traffic
  let avgSpeedKmH = 22; // default urban speed with traffic
  if (dest === 'darjeeling' || dest === 'nainital') {
    avgSpeedKmH = 18; // mountain switchbacks
  } else if (dest === 'kashmir') {
    avgSpeedKmH = 25; // scenic highway & boulevard
  }

  const rawMinutes = (dist / avgSpeedKmH) * 60;
  // Add buffer for boarding/parking/signals (minimum 10 mins for transit between separate venues)
  return Math.max(10, Math.round(rawMinutes + 5));
}
