export type Language = 'en' | 'hi' | 'bn' | 'mr';

export interface LanguageOption {
  code: Language;
  label: string;
  nativeLabel: string;
  shortLabel: string;
}

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English', nativeLabel: 'English', shortLabel: 'ENG' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी', shortLabel: 'HIN' },
  { code: 'bn', label: 'Bengali', nativeLabel: 'বাংলা', shortLabel: 'BEN' },
  { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी', shortLabel: 'MAR' }
];

export type TranslationKey =
  // App & Brand
  | 'app_name'
  | 'app_tagline'
  | 'adaptive_badge'
  | 'nav_home'
  | 'nav_new_trip'
  | 'nav_live_mode'
  | 'nav_review'
  | 'nav_demo'
  | 'nav_plan_version'
  | 'status_on_track'
  | 'status_minor_delay'
  | 'status_action_needed'
  // Home Page
  | 'hero_badge'
  | 'hero_subtitle'
  | 'hero_description'
  | 'cta_start_planning'
  | 'cta_explore_demo'
  | 'feature_disruption_title'
  | 'feature_disruption_desc'
  | 'feature_replan_title'
  | 'feature_replan_desc'
  | 'feature_destinations_title'
  | 'feature_destinations_desc'
  | 'why_adaptgo_title'
  | 'why_adaptgo_subtitle'
  | 'why_point1_title'
  | 'why_point1_desc'
  | 'why_point2_title'
  | 'why_point2_desc'
  | 'why_point3_title'
  | 'why_point3_desc'
  | 'explore_destinations_title'
  | 'explore_destinations_subtitle'
  | 'plan_destination_btn'
  | 'footer_motto'
  | 'footer_credits'
  // Create Trip Page
  | 'create_title'
  | 'create_subtitle'
  | 'nl_input_label'
  | 'nl_input_placeholder'
  | 'nl_input_hint'
  | 'nl_parse_btn'
  | 'nl_parsing'
  | 'form_destination'
  | 'form_date'
  | 'form_start_time'
  | 'form_end_time'
  | 'form_travelers'
  | 'form_budget'
  | 'form_interests'
  | 'form_travel_style'
  | 'form_walking'
  | 'form_transport'
  | 'style_relaxed'
  | 'style_balanced'
  | 'style_fast_paced'
  | 'walking_low'
  | 'walking_moderate'
  | 'walking_high'
  | 'transport_cab'
  | 'transport_walking'
  | 'transport_public'
  | 'transport_rental'
  | 'interest_history'
  | 'interest_culture'
  | 'interest_nature'
  | 'interest_scenic'
  | 'interest_food'
  | 'interest_shopping'
  | 'interest_adventure'
  | 'interest_spiritual'
  | 'btn_generate_plan'
  | 'btn_generating_plan'
  // Review Trip Page
  | 'review_step_badge'
  | 'review_title'
  | 'review_metric_duration'
  | 'review_metric_budget'
  | 'review_metric_locked'
  | 'review_metric_activities'
  | 'review_tab_split'
  | 'review_tab_timeline'
  | 'review_tab_map'
  | 'review_btn_start_trip'
  | 'review_tip_locked'
  | 'action_lock'
  | 'action_unlock'
  | 'action_move_up'
  | 'action_move_down'
  | 'action_remove'
  // Live Trip Page
  | 'live_header_title'
  | 'live_header_subtitle'
  | 'live_sim_title'
  | 'live_sim_desc'
  | 'live_sim_rain'
  | 'live_sim_traffic'
  | 'live_sim_closure'
  | 'live_sim_custom'
  | 'live_alert_title'
  | 'live_alert_impact'
  | 'live_alert_action_needed'
  | 'live_btn_replan'
  | 'live_btn_resolve'
  | 'live_btn_replanning'
  | 'live_history_btn'
  | 'live_map_title'
  | 'live_timeline_title'
  // Destinations
  | 'dest_kolkata'
  | 'dest_kolkata_desc'
  | 'dest_nainital'
  | 'dest_nainital_desc'
  | 'dest_darjeeling'
  | 'dest_darjeeling_desc'
  | 'dest_kashmir'
  | 'dest_kashmir_desc'
  // Dynamic & Section labels
  | 'section_destination'
  | 'section_destinations'
  | 'section_destinations_desc'
  | 'section_logistics'
  | 'label_trip_date'
  | 'label_start_time'
  | 'label_end_time'
  | 'label_travelers'
  | 'label_budget'
  | 'section_preferences'
  | 'label_interests'
  | 'label_walking'
  | 'label_style'
  | 'label_transport'
  | 'transport_transit'
  | 'section_must_visit'
  | 'section_avoid'
  | 'section_avoid_desc'
  | 'btn_generate_itinerary'
  | 'review_itinerary_title'
  | 'review_itinerary_subtitle'
  | 'metric_hours'
  | 'metric_locked'
  | 'btn_start_trip'
  | 'tab_timeline'
  | 'tab_map'
  | 'timeline_stops'
  | 'lock_tooltip'
  | 'map_route_title'
  | 'live_itinerary_title'
  | 'live_gps'
  | 'monitoring_realtime'
  | 'rain'
  | 'what_changed'
  | 'current_activity'
  | 'time_remaining'
  | 'allocated_duration'
  | 'mark_completed'
  | 'up_next_stop'
  | 'remaining_itinerary'
  | 'demo_simulator'
  | 'simulate_rain'
  | 'simulate_traffic'
  | 'simulate_closure'
  | 'simulate_delay'
  | 'simulate_early'
  | 'reset'
  | 'nl_live_placeholder';
